### ISSUE TITLE
Support for GREL md5 and sha1 functions

### ISSUE THREAD

**Issue by CyberDaedalus00** [RMLio/rmlmapper-java#100]
Are there any plans to add support for GREL's md5 and sha1 functions?  I noticed in they were comments out.

**Comment by bjdmeest** [comment]
Hi @CyberDaedalus00 , these functions are now implemented v0.6.1 of https://github.com/FnOio/grel-functions-java , and included in release [v4.9.2](https://github.com/RMLio/rmlmapper-java/releases/tag/v4.9.2), hopefully this works for you!

**Comment by paulakeen** [comment]
I'm interested in this topic, but cannot find examples of usage...any URL you could redirect me to, please?

**Comment by bjdmeest** [comment]
The resulting mapping file would be very similar to the one at https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/rml-fno-test-cases/RMLFNOTC0001-CSV/mapping.ttl , but then using `http://users.ugent.be/~bjdmeest/function/grel.ttl#string_md5` instead of `http://users.ugent.be/~bjdmeest/function/grel.ttl#toUpperCase` on [line 34](https://github.com/RMLio/rmlmapper-java/blob/master/src/test/resources/rml-fno-test-cases/RMLFNOTC0001-CSV/mapping.ttl#L34).
You can check all by default supported functions, and how to invoke their parameters at https://rml.io/docs/rmlmapper/default-functions/
